### ISSUE TITLE
Parameters seen only on commented lines are treated as active parameters and don't offer option to "Remove Unused"

### ISSUE THREAD

**Issue by beccanet** [adamfoneil/SqlChartify.Issues#16]
To repro, open a query with parameters, and comment out all lines referencing that parameter.  Even after saving, the parameter shows up on the right pane without the "Remove Unused" button.  If you remove the "@" or put a space between the "@" and the parameter name THEN you see the Remove Unused button.  The right pane shouldn't look on commented lines  (in this case, starting with "--") for active parameters.

**Comment by adamfoneil** [comment]
As a regex problem, I'm not sure how feasible this will really be to solve
