### ISSUE TITLE
Remove Unused button isn't working (again).

### ISSUE THREAD

**Issue by beccanet** [adamfoneil/SqlChartify.Issues#17]
This functionality worked well yesterday for a brief time, but it's not working currently.

**Comment by adamfoneil** [comment]
Audio is super quiet unfortunately, but here is repro.
https://1drv.ms/v/s!AvguHRnyJtWMl4kvq-2yDIfLy_b7OA?e=v4P46f
param removal works when report has been saved, but not when it's been modified and has unsaved changes
