### ISSUE TITLE
Righthand "search" is really a filter and should be down with the other filters, and should search the query as well as the title

### ISSUE THREAD

**Issue by beccanet** [adamfoneil/SqlChartify.Issues#21]

**Comment by adamfoneil** [comment]
When filter matches SQL, it would be really neat if the SQL fragment revealed itself with a slide down. As it is, the SQL doesn't appear on the home page, so without this you wouldn't know why a filter was producing a result if it matched SQL only

**Comment by adamfoneil** [comment]
in latest release
